/**
 * POST /api/field-trips-pdf
 * Generates a real PDF of field trip suggestions using @react-pdf/renderer.
 * Returns application/pdf with Content-Disposition: attachment.
 * Auth required.
 */

import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  pdf,
} from "@react-pdf/renderer";

// Teal brand color
const TEAL = "#1a5c5a";
const LIGHT_TEAL = "#4a9d8f";
const GRAY = "#6b6b6b";
const DARK = "#2d2d2d";

const styles = StyleSheet.create({
  page: {
    fontFamily: "Helvetica",
    padding: 48,
    backgroundColor: "#ffffff",
    color: DARK,
  },
  header: {
    marginBottom: 24,
    borderBottomWidth: 2,
    borderBottomColor: LIGHT_TEAL,
    paddingBottom: 12,
  },
  title: {
    fontSize: 22,
    fontFamily: "Helvetica-Bold",
    color: TEAL,
    marginBottom: 4,
  },
  meta: {
    fontSize: 10,
    color: GRAY,
  },
  tripCard: {
    marginBottom: 20,
    paddingLeft: 12,
    borderLeftWidth: 3,
    borderLeftColor: LIGHT_TEAL,
  },
  tripTitle: {
    fontSize: 13,
    fontFamily: "Helvetica-Bold",
    color: TEAL,
    marginBottom: 6,
  },
  line: {
    fontSize: 10,
    color: DARK,
    marginBottom: 3,
    lineHeight: 1.5,
  },
  label: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: DARK,
  },
  footer: {
    position: "absolute",
    bottom: 32,
    left: 48,
    right: 48,
    fontSize: 8,
    color: GRAY,
    textAlign: "center",
    borderTopWidth: 1,
    borderTopColor: "#e0e0e0",
    paddingTop: 6,
  },
});

/** Split a suggestion string into title + body lines, stripping markdown symbols */
function parseSuggestion(raw: string): { title: string; lines: string[] } {
  const lines = raw
    .split("\n")
    .map((l) => l.replace(/^[*#\-\s]+/, "").trim())
    .filter(Boolean);
  const title = lines[0]?.replace(/^\d+\.\s*/, "").replace(/\*\*/g, "") ?? "";
  const body = lines.slice(1).map((l) => l.replace(/\*\*/g, ""));
  return { title, lines: body };
}

/** Split a body line into optional label + rest */
function parseBodyLine(line: string): { label?: string; rest: string } {
  const match = line.match(/^([^:]{2,30}):\s*(.+)$/);
  if (match) return { label: match[1], rest: match[2] };
  return { rest: line };
}

function FieldTripPdf({
  subject,
  zip,
  distance,
  suggestions,
}: {
  subject: string;
  zip: string;
  distance: string;
  suggestions: string[];
}) {
  return React.createElement(
    Document,
    null,
    React.createElement(
      Page,
      { size: "LETTER", style: styles.page },
      // Header
      React.createElement(
        View,
        { style: styles.header },
        React.createElement(Text, { style: styles.title }, `Field Trip Ideas: ${subject}`),
        React.createElement(
          Text,
          { style: styles.meta },
          `Near ${zip} within ${distance} miles`
        )
      ),
      // Trip cards
      ...suggestions.map((raw, i) => {
        const { title, lines } = parseSuggestion(raw);
        return React.createElement(
          View,
          { key: i, style: styles.tripCard },
          React.createElement(Text, { style: styles.tripTitle }, title || `Suggestion ${i + 1}`),
          ...lines.map((line, j) => {
            const { label, rest } = parseBodyLine(line);
            if (label) {
              return React.createElement(
                View,
                { key: j, style: { flexDirection: "row", marginBottom: 3 } },
                React.createElement(Text, { style: styles.label }, `${label}: `),
                React.createElement(Text, { style: styles.line }, rest)
              );
            }
            return React.createElement(Text, { key: j, style: styles.line }, line);
          })
        );
      }),
      // Footer
      React.createElement(
        Text,
        { style: styles.footer, fixed: true },
        "Generated by Unbound — unboundlearner.com"
      )
    )
  );
}

export async function POST(request: Request) {
  try {
    // Auth required
    const supabase = await createClient();
    const { data: { user }, error: authError } = await supabase.auth.getUser();
    if (authError || !user) {
      return NextResponse.json({ error: "Not authenticated" }, { status: 401 });
    }

    const body = await request.json() as {
      subject?: string;
      zip?: string;
      distance?: string;
      suggestions?: string[];
    };

    const { subject, zip, distance, suggestions } = body;

    if (!subject || !zip || !Array.isArray(suggestions) || suggestions.length === 0) {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
    }

    // Generate real PDF bytes via @react-pdf/renderer
    const doc = React.createElement(FieldTripPdf, {
      subject,
      zip: zip ?? "",
      distance: distance ?? "25",
      suggestions,
    });

    const pdfBytes = await pdf(doc as React.ReactElement).toBuffer();
    const filename = `field-trips-${subject.replace(/\s+/g, "-").toLowerCase()}.pdf`;

    return new Response(pdfBytes, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${filename}"`,
      },
    });
  } catch (err) {
    console.error("[field-trips-pdf] Error:", err);
    return NextResponse.json({ error: "PDF generation failed" }, { status: 500 });
  }
}
