"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import dynamic from "next/dynamic";
import type { GeneratedPlan } from "@/lib/agents";

// Dynamically import PDFDownloadLink so it only renders client-side
// (@react-pdf/renderer can't run in SSR)
const PDFDownloadLink = dynamic(
  () => import("@react-pdf/renderer").then((m) => m.PDFDownloadLink),
  { ssr: false }
);

const PlanPDF = dynamic(() => import("@/lib/PlanPDF"), { ssr: false });

export default function PlanPage() {
  const { id } = useParams<{ id: string }>();
  const [plan, setPlan] = useState<GeneratedPlan | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!id) return;

    async function fetchPlan() {
      try {
        const res = await fetch(`/api/get-plan/${id}`);
        if (!res.ok) {
          const data = await res.json();
          throw new Error(data.error || "Plan not found");
        }
        const data = await res.json();
        setPlan(data);
      } catch (err: unknown) {
        setError(
          err instanceof Error ? err.message : "Failed to load plan"
        );
      } finally {
        setLoading(false);
      }
    }

    fetchPlan();
  }, [id]);

  if (loading) {
    return (
      <main className="min-h-screen bg-[#faf9f6] flex items-center justify-center">
        <div className="text-center">
          <div className="text-4xl mb-4">🌱</div>
          <p className="text-[#5b8f8a] font-medium">Loading your plan…</p>
        </div>
      </main>
    );
  }

  if (error || !plan) {
    return (
      <main className="min-h-screen bg-[#faf9f6] flex items-center justify-center px-4">
        <div className="text-center max-w-sm">
          <div className="text-4xl mb-4">😔</div>
          <h1 className="text-xl font-bold text-[#2d2d2d] mb-2">
            Plan not found
          </h1>
          <p className="text-[#8a8580] mb-6">
            {error || "This plan may have expired (plans last 24 hours)."}
          </p>
          <a
            href="/profile"
            className="inline-block bg-[#5b8f8a] text-white font-semibold px-6 py-3 rounded-xl"
          >
            Create a new plan
          </a>
        </div>
      </main>
    );
  }

  const date = new Date(plan.generatedAt).toLocaleDateString("en-US", {
    weekday: "long",
    month: "long",
    day: "numeric",
  });

  // Convert the plan text to display-ready HTML-ish sections
  const planLines = plan.plan.split("\n");

  return (
    <main className="min-h-screen bg-[#faf9f6]">
      {/* Header bar */}
      <div className="bg-[#5b8f8a] text-white px-4 py-4">
        <div className="max-w-3xl mx-auto flex items-center justify-between">
          <div>
            <span className="font-bold text-lg">Unbound</span>
            <p className="text-sm text-white/80 mt-0.5">
              {plan.profile.childName}&apos;s Plan · {date}
            </p>
          </div>
          {/* PDF download button — only renders client-side */}
          <PDFDownloadLink
            document={
              <PlanPDF
                planText={plan.plan}
                childName={plan.profile.childName}
                generatedAt={plan.generatedAt}
              />
            }
            fileName={`unbound-plan-${plan.profile.childName.toLowerCase()}-${new Date(plan.generatedAt).toISOString().slice(0, 10)}.pdf`}
          >
            {({ loading: pdfLoading }) => (
              <button className="bg-white text-[#5b8f8a] font-semibold text-sm px-4 py-2 rounded-lg hover:bg-[#e8f4f3] transition-colors">
                {pdfLoading ? "Building PDF…" : "⬇ Download PDF"}
              </button>
            )}
          </PDFDownloadLink>
        </div>
      </div>

      {/* Plan content */}
      <div className="max-w-3xl mx-auto px-4 py-8">
        <article className="bg-white rounded-2xl shadow-sm border border-[#e8e4e0] p-6 sm:p-8 prose-custom">
          <PlanContent lines={planLines} />
        </article>

        {/* Agent credits */}
        <div className="mt-8">
          <h2 className="text-sm font-semibold text-[#8a8580] uppercase tracking-wide mb-4">
            Generated by the Unbound Agent Team
          </h2>
          <div className="grid sm:grid-cols-2 gap-3">
            {plan.agentOutputs.map((agent) => (
              <div
                key={agent.subject}
                className={`flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm ${
                  agent.error
                    ? "bg-red-50 text-red-600"
                    : "bg-[#e8f4f3] text-[#3d6e69]"
                }`}
              >
                <span className="font-medium">{agent.agentName}</span>
                <span className="text-xs opacity-70">· {agent.subject}</span>
                {agent.error && (
                  <span className="text-xs ml-auto">⚠ unavailable</span>
                )}
              </div>
            ))}
          </div>
        </div>

        {/* Footer CTA */}
        <div className="mt-10 text-center">
          <p className="text-[#8a8580] text-sm mb-3">
            Want a plan for another day? It&apos;s always just $9.
          </p>
          <a
            href="/profile"
            className="inline-block bg-[#5b8f8a] text-white font-semibold px-6 py-3 rounded-xl text-sm hover:bg-[#3d6e69] transition-colors"
          >
            Create Another Plan
          </a>
        </div>
      </div>
    </main>
  );
}

/**
 * Render markdown-ish plan text as styled React elements.
 * Handles # ## ### headings, --- dividers, and plain paragraphs.
 */
function PlanContent({ lines }: { lines: string[] }) {
  return (
    <div className="space-y-1">
      {lines.map((line, i) => {
        const trimmed = line.trim();

        if (trimmed.startsWith("# ")) {
          return (
            <h1 key={i} className="text-2xl font-bold text-[#2d2d2d] mt-6 mb-2">
              {trimmed.slice(2)}
            </h1>
          );
        }
        if (trimmed.startsWith("## ")) {
          return (
            <h2 key={i} className="text-xl font-bold text-[#5b8f8a] mt-6 mb-2">
              {trimmed.slice(3)}
            </h2>
          );
        }
        if (trimmed.startsWith("### ")) {
          return (
            <h3 key={i} className="text-base font-bold text-[#2d2d2d] mt-4 mb-1">
              {trimmed.slice(4)}
            </h3>
          );
        }
        if (trimmed === "---") {
          return <hr key={i} className="border-[#e8e4e0] my-4" />;
        }
        if (trimmed === "") {
          return <div key={i} className="h-2" />;
        }
        return (
          <p key={i} className="text-[#2d2d2d] leading-relaxed text-sm sm:text-base">
            {trimmed}
          </p>
        );
      })}
    </div>
  );
}
