"use client";

/**
 * React PDF document component for Unbound lesson plans.
 * Uses @react-pdf/renderer — renders server-safe PDF via client-side download.
 */

import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
} from "@react-pdf/renderer";

// Register Inter font for a clean look
Font.register({
  family: "Inter",
  fonts: [
    {
      src: "https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfAZ9hiJ-Ek-_EeA.woff",
      fontWeight: 400,
    },
    {
      src: "https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuI6fAZ9hiJ-Ek-_EeA.woff",
      fontWeight: 700,
    },
  ],
});

const TEAL = "#5b8f8a";
const CREAM = "#faf9f6";
const DARK = "#2d2d2d";
const GRAY = "#8a8580";
const TEAL_LIGHT = "#e8f4f3";

const styles = StyleSheet.create({
  page: {
    backgroundColor: CREAM,
    fontFamily: "Inter",
    paddingHorizontal: 48,
    paddingVertical: 48,
    color: DARK,
  },
  header: {
    marginBottom: 24,
    borderBottomWidth: 2,
    borderBottomColor: TEAL,
    paddingBottom: 12,
  },
  brandName: {
    fontSize: 11,
    color: TEAL,
    fontWeight: 700,
    letterSpacing: 1.5,
    textTransform: "uppercase",
  },
  title: {
    fontSize: 22,
    fontWeight: 700,
    color: DARK,
    marginTop: 6,
    lineHeight: 1.3,
  },
  dateText: {
    fontSize: 10,
    color: GRAY,
    marginTop: 4,
  },
  // Plan body — render as plain paragraphs split by newline
  planText: {
    fontSize: 11,
    lineHeight: 1.7,
    color: DARK,
    marginBottom: 4,
  },
  heading1: {
    fontSize: 16,
    fontWeight: 700,
    color: DARK,
    marginTop: 18,
    marginBottom: 6,
  },
  heading2: {
    fontSize: 13,
    fontWeight: 700,
    color: TEAL,
    marginTop: 14,
    marginBottom: 4,
  },
  heading3: {
    fontSize: 11,
    fontWeight: 700,
    color: DARK,
    marginTop: 10,
    marginBottom: 3,
  },
  divider: {
    borderBottomWidth: 1,
    borderBottomColor: TEAL_LIGHT,
    marginVertical: 10,
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 48,
    right: 48,
    textAlign: "center",
    fontSize: 9,
    color: GRAY,
  },
});

interface Props {
  planText: string;
  childName: string;
  generatedAt: string;
}

/**
 * Parse the plan text into renderable PDF nodes.
 * Handles markdown-style headings (# ## ###) and paragraph breaks.
 */
function renderPlanContent(text: string) {
  const lines = text.split("\n");
  const elements: React.ReactElement[] = [];

  lines.forEach((line, i) => {
    const trimmed = line.trim();

    if (trimmed.startsWith("# ")) {
      elements.push(
        <Text key={i} style={styles.heading1}>
          {trimmed.slice(2)}
        </Text>
      );
    } else if (trimmed.startsWith("## ")) {
      elements.push(
        <Text key={i} style={styles.heading2}>
          {trimmed.slice(3)}
        </Text>
      );
    } else if (trimmed.startsWith("### ")) {
      elements.push(
        <Text key={i} style={styles.heading3}>
          {trimmed.slice(4)}
        </Text>
      );
    } else if (trimmed === "---") {
      elements.push(<View key={i} style={styles.divider} />);
    } else if (trimmed === "") {
      // Blank line — small gap
      elements.push(<Text key={i} style={{ fontSize: 4 }}>{" "}</Text>);
    } else {
      elements.push(
        <Text key={i} style={styles.planText}>
          {trimmed}
        </Text>
      );
    }
  });

  return elements;
}

export default function PlanPDF({ planText, childName, generatedAt }: Props) {
  const date = new Date(generatedAt).toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.brandName}>Unbound</Text>
          <Text style={styles.title}>{childName}&apos;s Lesson Plan</Text>
          <Text style={styles.dateText}>{date}</Text>
        </View>

        {/* Plan content */}
        <View>{renderPlanContent(planText)}</View>

        {/* Footer */}
        <Text style={styles.footer}>
          Generated by Unbound · unboundlearn.com · {date}
        </Text>
      </Page>
    </Document>
  );
}
